services:
  app:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8gb'
    volumes:
      - ./:/aiups
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ""               # 禁用 token
      JUPYTER_PASSWORD: ""            # 禁用密碼
      JUPYTER_DISABLE_CHECK_XSRF: "true"  # 禁用 XSRF 檢查
    working_dir: /aiups
    image: aiups-automl:24.12  # 設定映像名稱與版本
    ports:
      - "8888:8888"
    tty: true
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token='aaa'", "--NotebookApp.password=''"]
